### ISSUE TITLE
Listing and Deleting Shortcuts

### ISSUE THREAD

**Issue by sohcah** [lovetodream/capacitor-plugin-siri-shortcuts#2]
Currently, this plugin only allows for donating shortcuts, however the native iOS SDK provides the ability to list and delete existing shortcuts, which would be very helpful. Could this be implemented into this plugin?

**Comment by lovetodream** [comment]
Sure, this is already on my todo list, but until now I never needed it for my projects. 
I will definitely add it in the next few days.

**Comment by lovetodream** [comment]
I've added the ability to delete shortcuts. But I didn't find a native iOS ability to list existing shortcuts. Can you provide a link to the documentation?

**Comment by sohcah** [comment]
Ah, looks like I was wrong about the ability to list shortcuts, sorry. I guess I'll have to store that myself. :) 

Thank you so much for adding the deletion functionality, that will certainly be very helpful! You're doing a great job making this plugin!

**Comment by lovetodream** [comment]
Thank you very much, it really means a lot to me
