### ISSUE TITLE
Present shortcuts

### ISSUE THREAD

**Issue by mishelson** [lovetodream/capacitor-plugin-siri-shortcuts#3]
I have used similar plugins of sirishorts in previous versions of capacitor, we could add the "Present" function to create the "add to siri" within our application. It would be incredible to be able to do it to facilitate the user experience when adding the shortcuts either by voice or directly by text.

somethings like this:
![siripresent](https://user-images.githubusercontent.com/3543698/136630632-b9c0e7d3-490e-4b83-8334-69f43a3270d8.png)

**Comment by lovetodream** [comment]
Yeah, that seems like a great addition, I'll look into this next week.

**Comment by lovetodream** [comment]
I've added the feature with version 2.2.0

**Comment by mishelson** [comment]
To Native ->  SiriShortcuts present 96927831
⚡️  Error: Plugin SiriShortcuts does not respond to method call "present" using selector "present:".
⚡️  Ensure plugin method exists, uses @objc in its declaration, and arguments match selector without callbacks in CAP_PLUGIN_METHOD.
⚡️  Learn more: https://capacitorjs.com/docs/plugins/ios/#defining-methods
2021-10-15 17:26:17.526034-0600 App[6688:50955] [boringssl] boringssl_metrics_log_metric_block_invoke(144) Failed to log metrics
