### ISSUE TITLE
CommonJS entrypoint

### ISSUE THREAD

**Issue by RobSchilderr** [lovetodream/capacitor-plugin-siri-shortcuts#43]
Hey, what a great idea this is! Will you update this to Capacitor v4? Cant wait to try it out and see all the new iOS 16 possibilities

**Comment by lovetodream** [comment]
Hey, thanks. The newest version of the plugin should already work with v4. Did you try it out already? If it doesn't work, I'd appreciate if you can attach the error logs.

**Comment by RobSchilderr** [comment]
I will check it out tomorrow! Thanks so much

**Comment by lovetodream** [comment]
Let me know if something doesn't work or if you have any additional feature requests

**Comment by RobSchilderr** [comment]
> Let me know if something doesn't work or if you have any additional feature requests

Hey Timo, sure thing! Upon building with NextJS I am getting an error. I will try to describe it:



**Describe the bug**
Our project's web assets (webpack) build is failing if the following `import { SiriShortcuts } from 'capacitor-plugin-siri-shorts` is defined somewhere in the code.


The error is the following:

``` Collecting page data .node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
            ^
ReferenceError: capacitorExports is not defined
    at Object.<anonymous> (/node_modules/capacitor-plugin-siri-shorts/dist/plugin.js:12:8)```


I am using the NextJS's next build command to run build.

**To Reproduce**
Steps to reproduce the behavior:

1. Build a project with (NextJS and Capacitor)[https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter]
2. Follow installation steps of `capacitor-plugin-siri-shorts`
3. Run yarn build
```

**Possible solution**

Change `  "main": "dist/plugin.js"` to  `"main": "dist/plugin.cjs.js",` in the `package.json`

This morning I was looking for a solution for us. I have to say that I have no experience with Swift or capacitor plugins. But I managed to get `next build` working  if I made this change.

I read about another (plugin)[https://github.com/capacitor-community/bluetooth-le/issues/12] that had this issue too. 

Let me know if this is the correct solution! I haven't managed to get the plugin to work, but I'll continue to try this Sunday.

Thanks so much for replying @lovetodream

**Comment by lovetodream** [comment]
Even through I cannot reproduce your issue, I've found out that the boilerplate for the package.json for capacitor plugins has changed to the cjs-way you're suggesting https://github.com/ionic-team/create-capacitor-plugin/blob/main/assets/plugin-template/package.json.mustache#L5
I'll release an update including the changes as a breaking change with v3.0.0 of the plugin, because I do not know how this affects existing projects.

**Comment by RobSchilderr** [comment]
> Even through I cannot reproduce your issue, I've found out that the boilerplate for the package.json for capacitor plugins has changed to the cjs-way you're suggesting https://github.com/ionic-team/create-capacitor-plugin/blob/main/assets/plugin-template/package.json.mustache#L5 I'll release an update including the changes as a breaking change with v3.0.0 of the plugin, because I do not know how this affects existing projects.

Cheers man! Will let you know after the update how things go.
