### ISSUE TITLE
Update to Capacitor 5

### ISSUE THREAD

**Issue by AlexanderMelde** [lovetodream/capacitor-plugin-siri-shortcuts#54]
Hi Timo,

according to your package.json, this plugin only supports capacitor 3 and 4. 
In order to meet Google Plays [new Target API requirement](https://support.google.com/googleplay/android-developer/answer/11926878), updating to capacitor 5 is necessary.

A Guide on how to update plugins to capacitor 5.0 is described here: 
https://capacitorjs.com/docs/updating/plugins/5-0

There is an migration plugin available, so maybe updating can be done quite easily.

Do you think you could update your plugin, so I can continue using it?

Thank you for your support!

**Comment by lovetodream** [comment]
I've just published v5, let me know if it doesn't work. Thanks for your contribution!

**Comment by AlexanderMelde** [comment]
@lovetodream Thank you! I now integrated the update in our app and the shortcut features work just as well as before :) :+1:
